services:
  superset:
    image: nghia294/superset:4.1.3
    #container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - "8088:8088"
  minio:
    image: minio/minio
    #container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
  hive-postgres:
    image: postgres:17.2
    #container_name: hive-postgres
    ports:
      - 5431:5432
    volumes:
       - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB : metastore
  hive:
    image: starburstdata/hive:3.1.2-e.18
    #container_name: hive
    ports:
      - "9083:9083"
    environment:
        HIVE_INPUT_FORMAT: org.apache.hudi.hadoop.HoodieParquetInputFormat
        HIVE_METASTORE_DRIVER: org.postgresql.Driver
        HIVE_METASTORE_JDBC_URL: jdbc:postgresql://hive-postgres:5432/metastore
        HIVE_METASTORE_USER: postgres
        HIVE_METASTORE_PASSWORD: postgres
        HIVE_METASTORE_WAREHOUSE_DIR: s3a://gold/warehouse/
        S3_ENDPOINT: http://minio:9000
        S3_ACCESS_KEY: minioadmin
        S3_SECRET_KEY: minioadmin
        S3_PATH_STYLE_ACCESS: "true"
        REGION: ""
        GOOGLE_CLOUD_KEY_FILE_PATH: ""
        AZURE_ADL_CLIENT_ID: ""
        AZURE_ADL_CREDENTIAL: ""
        AZURE_ADL_REFRESH_URL: ""
        AZURE_ABFS_STORAGE_ACCOUNT: ""
        AZURE_ABFS_ACCESS_KEY: ""
        AZURE_WASB_STORAGE_ACCOUNT: ""
        AZURE_ABFS_OAUTH: ""
        AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
        AZURE_ABFS_OAUTH_CLIENT_ID: ""
        AZURE_ABFS_OAUTH_SECRET: ""
        AZURE_ABFS_OAUTH_ENDPOINT: ""
        AZURE_WASB_ACCESS_KEY: ""
        HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
  trino:
    image: trinodb/trino:465
    #container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/lib/hudi-trino-bundle-0.15.0.jar:/usr/lib/trino/plugin/hive/hudi-trino-bundle-0.15.0.jar